[build]
  base = "client"
  publish = "dist"
  command = "npm run build"

[dev]
  command = "npm run dev"
  port = 5173
  targetPort = 5173
  framework = "vite"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
