name: nakama-node
data_dir: './data/'

logger:
    level: 'debug'
    stdout: true
    file: ''

console:
    port: 10001
    username: 'admin'
    password: 'password'

socket:
    server_key: 'defaultkey'
    port: 10000
    max_message_size_bytes: 4096

runtime:
    js_entrypoint: 'build/index.js'

cors:
    allowed_headers: ['*']
    allowed_origins: ['*'] # For testing only - restrict to your origin for production!
