name: nakama-node
data_dir: './data/'

logger:
    level: 'debug'
    stdout: true
    file: ''

console:
    port: 10001
    username: 'admin'
    password: 'password'

socket:
    server_key: 'defaultkey'
    port: 10000
    max_message_size_bytes: 4096

runtime:
    js_entrypoint: 'build/index.js'
cors:
    enabled: true
    allow_origin: ['https://tic-tac-toe-lila.netlify.app', 'http://localhost:8080']
    allow_headers: ['*']
    allow_credentials: true
